{
  inputs,
  pkgs,
  lib,
  config,
  devenv-zsh,
  ...
}:
{
  imports = [ devenv-zsh.plugin ];
  zsh.enable = true;

  packages = with pkgs; [
    mkcert # For generating certificates
    nssTools # For installing the root certificate
  ];

  # Trust the certificates generated by mkcert
  scripts.install-certificate.exec = ''
    mkcert -install
  '';

  # This creates a local copy of Caddy that can bind to privileged ports like 80 and 443
  scripts.caddy-setcap.exec = lib.mkForce ''
    mkdir -p ./bin
    cp ${pkgs.caddy}/bin/caddy ./bin/caddy
    sudo setcap 'cap_net_bind_service=+ep' ./bin/caddy
  '';

  # This launces the local Caddy
  processes.caddy-local.exec = ''
    ${lib.replaceString "${pkgs.caddy}" "." config.processes.caddy.exec}
  '';
}
