{
  inputs,
  pkgs,
  lib,
  config,
  ...
}:
{
  packages = with pkgs; [
    mkcert # For generating certificates
    nssTools # For installing the root certificate
  ];

  # Trust the certificates generated by mkcert
  scripts.install-certificate.exec = ''
    mkcert -install
  '';

  # This creates a local copy of Apache that can bind to privileged ports like 80 and 443
  scripts.apache-setcap.exec = lib.mkForce ''
    mkdir -p ./bin
    cp ${pkgs.apacheHttpd}/bin/httpd ./bin/httpd
    sudo setcap 'cap_net_bind_service=+ep' ./bin/httpd
  '';

  # This launces the local Apache
  processes.apache-local.exec = ''${lib.replaceString "${pkgs.apacheHttpd
  }" "." config.processes.apache.exec}'';
}
