{
  pkgs,
  ...
}:
{
  packages = with pkgs; [
    mkcert # For generating certificates
    nssTools # For installing the root certificate
  ];

  # Trust the certificates generated by mkcert
  scripts.install-certificate.exec = ''
    mkcert -install
  '';
}
