{
  pkgs,
  lib,
  devenv-zsh,
  ...
}:
{
  imports = [ devenv-zsh.plugin ];
  zsh.enable = true;

  packages = with pkgs; [
    mkcert # For generating certificates
    nssTools # For installing the root certificate
  ];

  # Trust the certificates generated by mkcert
  scripts.install-certificate.exec = ''
    mkcert -install
  '';

  # This creates a local copy of SASS
  scripts.local-sass.exec = lib.mkForce ''
    mkdir -p ./bin
    cp ${pkgs.dart-sass}/bin/sass ./bin/sass
  '';
}
